/* =============================================================================
   FAT - FPT Academic Tracker
   03_seed_demo.sql : demo accounts and academic records.

   Run AFTER 02_seed_master.sql.

   DEMO ACCOUNTS
   ---------------------------------------------------------------------------
     admin      / Admin@123     (Admin)
     student01  / Student@123   (SE170001 - final year, ~78% progress, 1 retake)
     student02  / Student@123   (SE180002 - second year, ~53% progress)
     student03  / Student@123   (SE190003 - first year,  ~14% progress)
   ---------------------------------------------------------------------------

   Scores are generated by a DETERMINISTIC formula over the row ids - never
   RAND(). Everyone who runs this script therefore gets byte-identical data, so
   if two machines disagree on a dashboard number the cause is definitely the
   code and never the data.
   ============================================================================= */

SET NOCOUNT ON;
GO

USE FAT;
GO

BEGIN TRANSACTION;
GO

/* -----------------------------------------------------------------------------
   Accounts

   PasswordHash values are real BCrypt hashes (work factor 11), verified with
   BCrypt.Net.Verify before being pasted here. No plaintext password is stored.
   ----------------------------------------------------------------------------- */
INSERT INTO dbo.AppUser (Username, PasswordHash, RoleId)
SELECT u.Username, u.PasswordHash, r.RoleId
FROM (VALUES
    (N'admin',     N'$2a$11$JJQiWDIKwyl.f89GLxktb.lx2BSbc.XhflOzX9V993TDFW0fQsAzW', N'Admin'),
    (N'student01', N'$2a$11$QhwqYB24gDf/DvwQ4Ccs/e5iK.ij6QcbYOb1gu.HJ6iF5HKLGEhXe', N'Student'),
    (N'student02', N'$2a$11$QhwqYB24gDf/DvwQ4Ccs/e5iK.ij6QcbYOb1gu.HJ6iF5HKLGEhXe', N'Student'),
    (N'student03', N'$2a$11$QhwqYB24gDf/DvwQ4Ccs/e5iK.ij6QcbYOb1gu.HJ6iF5HKLGEhXe', N'Student')
) AS u(Username, PasswordHash, RoleName)
JOIN dbo.Role r ON r.RoleName = u.RoleName;
GO

/* -----------------------------------------------------------------------------
   Student profiles
   ----------------------------------------------------------------------------- */
INSERT INTO dbo.Student (UserId, StudentCode, FullName, Email, DateOfBirth, EnrollmentDate, MajorId, Status)
SELECT au.UserId, s.StudentCode, s.FullName, s.Email, s.DateOfBirth, s.EnrollmentDate, m.MajorId, N'Active'
FROM (VALUES
    (N'student01', N'SE170001', N'Tran Nhat Long',  N'longtn.se170001@fpt.edu.vn', '2003-04-12', '2024-01-08'),
    (N'student02', N'SE180002', N'Nguyen Minh Anh', N'anhnm.se180002@fpt.edu.vn',  '2004-09-30', '2025-01-06'),
    (N'student03', N'SE190003', N'Le Hoang Phuc',   N'phuclh.se190003@fpt.edu.vn', '2005-11-21', '2026-01-05')
) AS s(Username, StudentCode, FullName, Email, DateOfBirth, EnrollmentDate)
JOIN dbo.AppUser au ON au.Username = s.Username
CROSS JOIN dbo.Major m
WHERE m.MajorCode = N'SE';
GO

/* -----------------------------------------------------------------------------
   Enrollment - the study path of the three students

   student01 deliberately FAILS CSD201 in FA24 and RETAKES it in SP25. That data
   exists to exercise the "only the latest attempt counts" rule (IsCounted) - an
   easy rule to get wrong, and getting it wrong inflates the GPA.
   ----------------------------------------------------------------------------- */
INSERT INTO dbo.Enrollment (StudentId, CourseId, SemesterId)
SELECT st.StudentId, c.CourseId, sm.SemesterId
FROM (VALUES
    -- ===== student01: terms 1-7 complete, currently on internship =====
    (N'SE170001', N'CSI104',  N'SP24'), (N'SE170001', N'PRF192',  N'SP24'),
    (N'SE170001', N'MAE101',  N'SP24'), (N'SE170001', N'CEA201',  N'SP24'),
    (N'SE170001', N'SSL101c', N'SP24'),

    (N'SE170001', N'PRO192',  N'SU24'), (N'SE170001', N'MAD101',  N'SU24'),
    (N'SE170001', N'OSG202',  N'SU24'), (N'SE170001', N'NWC204',  N'SU24'),
    (N'SE170001', N'SSG104',  N'SU24'),

    (N'SE170001', N'CSD201',  N'FA24'),          -- attempt 1: will FAIL
    (N'SE170001', N'DBI202',  N'FA24'), (N'SE170001', N'LAB211',  N'FA24'),
    (N'SE170001', N'WED201c', N'FA24'), (N'SE170001', N'IOT102',  N'FA24'),

    (N'SE170001', N'CSD201',  N'SP25'),          -- attempt 2: retake, PASSES
    (N'SE170001', N'PRJ301',  N'SP25'), (N'SE170001', N'SWE201c', N'SP25'),
    (N'SE170001', N'MAS291',  N'SP25'), (N'SE170001', N'ITE302c', N'SP25'),

    (N'SE170001', N'PRN212',  N'SU25'), (N'SE170001', N'SWP391',  N'SU25'),
    (N'SE170001', N'SWT301',  N'SU25'),

    (N'SE170001', N'PRN222',  N'FA25'), (N'SE170001', N'SWR302',  N'FA25'),
    (N'SE170001', N'SDN302',  N'FA25'),

    (N'SE170001', N'PMG201c', N'SP26'), (N'SE170001', N'EXE101',  N'SP26'),
    (N'SE170001', N'MLN111',  N'SP26'),

    (N'SE170001', N'OJT202',  N'SU26'),          -- current term: in progress

    -- ===== student02: terms 1-4 complete, term 5 in progress =====
    (N'SE180002', N'CSI104',  N'SP25'), (N'SE180002', N'PRF192',  N'SP25'),
    (N'SE180002', N'MAE101',  N'SP25'), (N'SE180002', N'CEA201',  N'SP25'),
    (N'SE180002', N'SSL101c', N'SP25'),

    (N'SE180002', N'PRO192',  N'SU25'), (N'SE180002', N'MAD101',  N'SU25'),
    (N'SE180002', N'OSG202',  N'SU25'), (N'SE180002', N'NWC204',  N'SU25'),
    (N'SE180002', N'SSG104',  N'SU25'),

    (N'SE180002', N'CSD201',  N'FA25'), (N'SE180002', N'DBI202',  N'FA25'),
    (N'SE180002', N'LAB211',  N'FA25'), (N'SE180002', N'WED201c', N'FA25'),
    (N'SE180002', N'IOT102',  N'FA25'),

    (N'SE180002', N'PRJ301',  N'SP26'), (N'SE180002', N'SWE201c', N'SP26'),
    (N'SE180002', N'MAS291',  N'SP26'), (N'SE180002', N'ITE302c', N'SP26'),

    (N'SE180002', N'PRN212',  N'SU26'), (N'SE180002', N'SWP391',  N'SU26'),
    (N'SE180002', N'SWT301',  N'SU26'),          -- current term: in progress

    -- ===== student03: first year =====
    (N'SE190003', N'CSI104',  N'SP26'), (N'SE190003', N'PRF192',  N'SP26'),
    (N'SE190003', N'MAE101',  N'SP26'), (N'SE190003', N'CEA201',  N'SP26'),
    (N'SE190003', N'SSL101c', N'SP26'),

    (N'SE190003', N'PRO192',  N'SU26'), (N'SE190003', N'MAD101',  N'SU26'),
    (N'SE190003', N'OSG202',  N'SU26'), (N'SE190003', N'NWC204',  N'SU26'),
    (N'SE190003', N'SSG104',  N'SU26')           -- current term: in progress
) AS e(StudentCode, CourseCode, SemesterCode)
JOIN dbo.Student  st ON st.StudentCode  = e.StudentCode
JOIN dbo.Course   c  ON c.CourseCode    = e.CourseCode
JOIN dbo.Semester sm ON sm.SemesterCode = e.SemesterCode;
GO

/* -----------------------------------------------------------------------------
   Grade - component scores

   Deterministic formula:
     base  = 5.8 + ((StudentId * 7 + CourseId * 13) % 38) / 10.0   -> 5.8 .. 9.5
     score = base + (((AssessmentId * 3 + EnrollmentId * 5) % 11) - 5) / 10.0
   i.e. a +/- 0.5 spread around the base, then clamped to [0, 10].
   ----------------------------------------------------------------------------- */

DECLARE @CurrentOrder INT = (SELECT DisplayOrder FROM dbo.Semester WHERE IsCurrent = 1);

-- (a) COMPLETED terms: every component has a score
INSERT INTO dbo.Grade (EnrollmentId, AssessmentId, Score)
SELECT
    e.EnrollmentId,
    a.AssessmentId,
    CAST(
        CASE
            WHEN raw.Val < 0  THEN 0
            WHEN raw.Val > 10 THEN 10
            ELSE raw.Val
        END AS DECIMAL(4,2))
FROM dbo.Enrollment e
JOIN dbo.Semester   s ON s.SemesterId = e.SemesterId
JOIN dbo.Assessment a ON a.CourseId   = e.CourseId
CROSS APPLY (
    SELECT Val =
        (5.8 + ((e.StudentId * 7 + e.CourseId * 13) % 38) / 10.0)
      + (((a.AssessmentId * 3 + e.EnrollmentId * 5) % 11) - 5) / 10.0
) AS raw
WHERE s.DisplayOrder < @CurrentOrder;

-- (b) CURRENT term: continuous-assessment marks only, no final exam yet
--     so FinalScore stays NULL and Status stays 'Studying'. This is the real
--     code path of the "courses in progress" screen, so it needs real data.
INSERT INTO dbo.Grade (EnrollmentId, AssessmentId, Score)
SELECT
    e.EnrollmentId,
    a.AssessmentId,
    CAST(
        CASE
            WHEN raw.Val < 0  THEN 0
            WHEN raw.Val > 10 THEN 10
            ELSE raw.Val
        END AS DECIMAL(4,2))
FROM dbo.Enrollment e
JOIN dbo.Semester   s ON s.SemesterId = e.SemesterId
JOIN dbo.Assessment a ON a.CourseId   = e.CourseId
CROSS APPLY (
    SELECT Val =
        (5.8 + ((e.StudentId * 7 + e.CourseId * 13) % 38) / 10.0)
      + (((a.AssessmentId * 3 + e.EnrollmentId * 5) % 11) - 5) / 10.0
) AS raw
WHERE s.DisplayOrder = @CurrentOrder
  AND a.Name IN (N'Assignment', N'Progress Test', N'Supervisor Evaluation');
GO

/* -----------------------------------------------------------------------------
   Force student01 to FAIL CSD201 on the first attempt (FA24)

   A final exam score of 3.0 is below MinScoreToPass 4.0, which fails the course
   under the regulation even though the weighted total might still reach 5.0.
   This is the "failed on a component" test case.
   ----------------------------------------------------------------------------- */
UPDATE g
SET Score = CASE WHEN a.Name = N'Final Exam' THEN 3.00 ELSE 4.50 END
FROM dbo.Grade g
JOIN dbo.Assessment a ON a.AssessmentId = g.AssessmentId
JOIN dbo.Enrollment e ON e.EnrollmentId = g.EnrollmentId
JOIN dbo.Student    s ON s.StudentId    = e.StudentId
JOIN dbo.Course     c ON c.CourseId     = e.CourseId
JOIN dbo.Semester   m ON m.SemesterId   = e.SemesterId
WHERE s.StudentCode  = N'SE170001'
  AND c.CourseCode   = N'CSD201'
  AND m.SemesterCode = N'FA24';
GO

/* -----------------------------------------------------------------------------
   Settle each course: FinalScore, LetterGrade, GradePoint, Status

   THIS IS THE FORMULA that GradeService in the application must reproduce
   exactly. If the app computes something different from this seed, the app is
   the one that is wrong.
   ----------------------------------------------------------------------------- */
WITH Calc AS (
    SELECT
        g.EnrollmentId,
        -- Final score: weighted sum rounded to one decimal place
        ROUND(SUM(g.Score * a.Weight), 1) AS FinalScore,
        -- How many components fell below their own minimum
        SUM(CASE WHEN a.MinScoreToPass IS NOT NULL AND g.Score < a.MinScoreToPass
                 THEN 1 ELSE 0 END)       AS MinViolations,
        COUNT(*)                          AS GradedCount
    FROM dbo.Grade g
    JOIN dbo.Assessment a ON a.AssessmentId = g.AssessmentId
    GROUP BY g.EnrollmentId
),
Complete AS (
    -- Only settle a course once ALL of its components have been graded
    SELECT c.*
    FROM Calc c
    JOIN dbo.Enrollment e ON e.EnrollmentId = c.EnrollmentId
    WHERE c.GradedCount = (SELECT COUNT(*) FROM dbo.Assessment a2 WHERE a2.CourseId = e.CourseId)
)
UPDATE e
SET FinalScore  = cp.FinalScore,
    LetterGrade = gs.LetterGrade,
    GradePoint  = gs.GradePoint,
    Status      = CASE WHEN cp.FinalScore >= 5.0 AND cp.MinViolations = 0
                       THEN N'Passed' ELSE N'Failed' END,
    UpdatedAt   = SYSUTCDATETIME()
FROM dbo.Enrollment e
JOIN Complete cp       ON cp.EnrollmentId = e.EnrollmentId
JOIN dbo.GradeScale gs ON cp.FinalScore >= gs.MinScore AND cp.FinalScore < gs.MaxScore;
GO

/* -----------------------------------------------------------------------------
   AttemptNo and IsCounted

   Rule: for each (student, course) pair only the MOST RECENT attempt counts
   toward the GPA. Earlier attempts stay in the transcript for history but are
   marked IsCounted = 0.
   ----------------------------------------------------------------------------- */
WITH Ranked AS (
    SELECT
        e.EnrollmentId,
        ROW_NUMBER() OVER (PARTITION BY e.StudentId, e.CourseId ORDER BY s.DisplayOrder ASC)  AS AttemptAsc,
        ROW_NUMBER() OVER (PARTITION BY e.StudentId, e.CourseId ORDER BY s.DisplayOrder DESC) AS AttemptDesc
    FROM dbo.Enrollment e
    JOIN dbo.Semester s ON s.SemesterId = e.SemesterId
)
UPDATE e
SET AttemptNo = r.AttemptAsc,
    IsCounted = CASE WHEN r.AttemptDesc = 1 THEN 1 ELSE 0 END
FROM dbo.Enrollment e
JOIN Ranked r ON r.EnrollmentId = e.EnrollmentId;
GO

/* -----------------------------------------------------------------------------
   AcademicPlan - plans for the remaining terms
   ----------------------------------------------------------------------------- */
INSERT INTO dbo.AcademicPlan (StudentId, PlanName, Note)
SELECT s.StudentId, p.PlanName, p.Note
FROM (VALUES
    (N'SE170001', N'Graduation plan 2027', N'Finish term 9 in SP27'),
    (N'SE180002', N'Third year plan',      N'Term 6 expected in FA26')
) AS p(StudentCode, PlanName, Note)
JOIN dbo.Student s ON s.StudentCode = p.StudentCode;
GO

INSERT INTO dbo.AcademicPlanItem (PlanId, CourseId, SemesterId, TargetTermNo, ExpectedScore, DisplayOrder)
SELECT pl.PlanId, c.CourseId, sm.SemesterId, i.TargetTermNo, i.ExpectedScore, i.DisplayOrder
FROM (VALUES
    (N'SE170001', N'SEP490',  N'SP27', 9, CAST(8.5 AS DECIMAL(4,2)), 1),
    (N'SE170001', N'EXE201',  N'SP27', 9, CAST(8.0 AS DECIMAL(4,2)), 2),
    (N'SE180002', N'PRN222',  N'FA26', 6, CAST(7.5 AS DECIMAL(4,2)), 1),
    (N'SE180002', N'SWR302',  N'FA26', 6, CAST(8.0 AS DECIMAL(4,2)), 2),
    (N'SE180002', N'SDN302',  N'FA26', 6, CAST(7.0 AS DECIMAL(4,2)), 3)
) AS i(StudentCode, CourseCode, SemesterCode, TargetTermNo, ExpectedScore, DisplayOrder)
JOIN dbo.Student      s  ON s.StudentCode   = i.StudentCode
JOIN dbo.AcademicPlan pl ON pl.StudentId    = s.StudentId
JOIN dbo.Course       c  ON c.CourseCode    = i.CourseCode
JOIN dbo.Semester     sm ON sm.SemesterCode = i.SemesterCode;
GO

/* -----------------------------------------------------------------------------
   Material - sample learning materials

   The payloads are real text (not empty blobs) so that Download produces a file
   with actual content on the very first run, without anyone uploading first.
   ----------------------------------------------------------------------------- */
INSERT INTO dbo.Material (CourseId, Title, Description, Category, FileName, ContentType, FileSizeBytes, UploadedByUserId)
SELECT c.CourseId, m.Title, m.Description, m.Category, m.FileName, m.ContentType,
       DATALENGTH(CONVERT(VARBINARY(MAX), m.Body)), au.UserId
FROM (VALUES
    (N'PRF192',  N'PRF192 - Chapter 1 slides',        N'Variables, data types, operators',    N'Slide',     N'PRF192-Chapter01.txt',     N'text/plain', N'PRF192 - Chapter 1: introduction to programming in C.'),
    (N'PRF192',  N'PRF192 - Week 1 lab exercises',    N'Ten loop and array exercises',        N'Exercise',  N'PRF192-Lab01.txt',         N'text/plain', N'PRF192 - Week 1 exercises: for and while loops, one-dimensional arrays.'),
    (N'PRO192',  N'PRO192 - OOP with Java summary',   N'Inheritance, polymorphism',           N'Textbook',  N'PRO192-OOP-Notes.txt',     N'text/plain', N'PRO192 - OOP summary: encapsulation, inheritance, polymorphism, abstraction.'),
    (N'DBI202',  N'DBI202 - Sample final exam',       N'Past paper with answers',             N'Exam',      N'DBI202-SampleFE.txt',      N'text/plain', N'DBI202 - Sample exam: ERD design, 3NF normalisation, advanced SQL queries.'),
    (N'DBI202',  N'DBI202 - Normalisation slides',    N'1NF, 2NF, 3NF, BCNF',                 N'Slide',     N'DBI202-Normalization.txt', N'text/plain', N'DBI202 - Database normalisation: 1NF, 2NF, 3NF and BCNF with examples.'),
    (N'CSD201',  N'CSD201 - Data structures notes',   N'Linked lists, trees, graphs',         N'Textbook',  N'CSD201-DSA.txt',           N'text/plain', N'CSD201 - Linked list, stack, queue, binary tree, graph traversal.'),
    (N'PRN212',  N'PRN212 - WPF and MVVM guide',      N'Binding, commands, data templates',   N'Reference', N'PRN212-WPF-MVVM.txt',      N'text/plain', N'PRN212 - WPF MVVM: data binding, ICommand, DataTemplate, dependency injection.'),
    (NULL,       N'Student handbook',                 N'Academic regulations and grading',    N'Reference', N'Student-Handbook.txt',     N'text/plain', N'Student handbook: academic regulations, the 10-point scale, graduation requirements.')
) AS m(CourseCode, Title, Description, Category, FileName, ContentType, Body)
LEFT JOIN dbo.Course c ON c.CourseCode = m.CourseCode
CROSS JOIN (SELECT UserId FROM dbo.AppUser WHERE Username = N'admin') AS au;
GO

-- File payloads, matched back by file name
INSERT INTO dbo.MaterialFile (MaterialId, Content)
SELECT m.MaterialId, CONVERT(VARBINARY(MAX), b.Body)
FROM dbo.Material m
JOIN (VALUES
    (N'PRF192-Chapter01.txt',     N'PRF192 - Chapter 1: introduction to programming in C.'),
    (N'PRF192-Lab01.txt',         N'PRF192 - Week 1 exercises: for and while loops, one-dimensional arrays.'),
    (N'PRO192-OOP-Notes.txt',     N'PRO192 - OOP summary: encapsulation, inheritance, polymorphism, abstraction.'),
    (N'DBI202-SampleFE.txt',      N'DBI202 - Sample exam: ERD design, 3NF normalisation, advanced SQL queries.'),
    (N'DBI202-Normalization.txt', N'DBI202 - Database normalisation: 1NF, 2NF, 3NF and BCNF with examples.'),
    (N'CSD201-DSA.txt',           N'CSD201 - Linked list, stack, queue, binary tree, graph traversal.'),
    (N'PRN212-WPF-MVVM.txt',      N'PRN212 - WPF MVVM: data binding, ICommand, DataTemplate, dependency injection.'),
    (N'Student-Handbook.txt',     N'Student handbook: academic regulations, the 10-point scale, graduation requirements.')
) AS b(FileName, Body) ON b.FileName = m.FileName;
GO

COMMIT TRANSACTION;
GO

/* =============================================================================
   Self-checks
   ============================================================================= */

-- 1. Every material must have content, and the recorded size must match it
IF EXISTS (
    SELECT 1 FROM dbo.Material m
    LEFT JOIN dbo.MaterialFile f ON f.MaterialId = m.MaterialId
    WHERE f.MaterialId IS NULL OR DATALENGTH(f.Content) <> m.FileSizeBytes
)
BEGIN
    THROW 50010, N'[03_seed] FAILED: a material is missing content or has a wrong FileSizeBytes.', 1;
END

-- 2. student01's CSD201 retake must be failed and excluded from the GPA
IF NOT EXISTS (
    SELECT 1 FROM dbo.Enrollment e
    JOIN dbo.Student s ON s.StudentId = e.StudentId
    JOIN dbo.Course  c ON c.CourseId  = e.CourseId
    WHERE s.StudentCode = N'SE170001' AND c.CourseCode = N'CSD201'
      AND e.Status = N'Failed' AND e.IsCounted = 0
)
BEGIN
    THROW 50011, N'[03_seed] FAILED: the CSD201 retake case for SE170001 is in the wrong state.', 1;
END

-- 3. No student may have the same course counted toward the GPA twice
IF EXISTS (
    SELECT StudentId, CourseId FROM dbo.Enrollment
    WHERE IsCounted = 1
    GROUP BY StudentId, CourseId HAVING COUNT(*) > 1
)
BEGIN
    THROW 50012, N'[03_seed] FAILED: a course is counted toward the GPA more than once.', 1;
END

-- 4. Courses in the current term must still be in progress
IF EXISTS (
    SELECT 1 FROM dbo.Enrollment e
    JOIN dbo.Semester s ON s.SemesterId = e.SemesterId
    WHERE s.IsCurrent = 1 AND e.Status <> N'Studying'
)
BEGIN
    THROW 50013, N'[03_seed] FAILED: a course in the current term has already been settled.', 1;
END

-- 5. Every completed course must carry a letter grade
IF EXISTS (
    SELECT 1 FROM dbo.Enrollment
    WHERE Status IN (N'Passed', N'Failed') AND (FinalScore IS NULL OR LetterGrade IS NULL)
)
BEGIN
    THROW 50014, N'[03_seed] FAILED: a completed course is missing its final score.', 1;
END
GO

PRINT '[03_seed_demo] OK - demo accounts and academic records loaded.';
GO
